version: '3'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  nginx_cache:
    image: nginx:alpine
    volumes:
      - ./statics:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
